### ISSUE TITLE
Links associated partners page

### ISSUE THREAD

**Issue by lwieneke** [impresso/impresso.github.io#21]
On the associated partners page several links open as relative links rather than pointing to the external website as they are supposed to.
http://impresso-project.ch/consortium/associated-partners/

e.g. Swiss Press Online 
http://impresso-project.ch/consortium/associated-partners/www.swisspressar-chives.ch

**Comment by PaulSchroeder** [comment]
Issue was resolved by adding "http" protocol where it was missing. 
changed http://www.swisspressar-chives.ch to http://newspaper.archives.rero.ch
