### ISSUE TITLE
Milestone flags point to wrong content

### ISSUE THREAD

**Issue by mduering** [impresso/impresso.github.io#27]
![fullscreen_3_20_18__10_21](https://user-images.githubusercontent.com/4408050/37649271-8465aea2-2c31-11e8-8273-97b6f5f30457.jpg)
When I click on the little “Milestone” flag, I see this:

Kick-off Meeting and First Workshop

We will hold our first consortium meeting and have our first workshop, dedicated to the identification of suitable newspapers and of feasible requirements with regard to Natural Language Processing (NLP) and interface design. Duration: 1 day, Place: Lausanne, Organisation: DHLAB, UZH, C2DH.

When i click on the line in the timeline directly, I get the correct text for the upcoming workshops. Could you check this please?

**Comment by PaulSchroeder** [comment]
quoting Daniele: 

> nobody clicks on that box!

>

**Comment by PaulSchroeder** [comment]
I disabled click events on the Milesone Box, and changed cursor on timeline to make it more obvious that timeline is clickable
