### ISSUE TITLE
no link assigned to email icon 

### ISSUE THREAD

**Issue by mduering** [impresso/impresso.github.io#29]
twitter and github is ok..

**Comment by PaulSchroeder** [comment]
are you referring to this icon?
![icons](https://user-images.githubusercontent.com/32929425/37664361-7ca10d40-2c5b-11e8-8570-f5985fe0bcb7.png)
href assigned to **mailto:info@impresso-project.ch**

**Comment by mduering** [comment]
yes, that's the one
