### ISSUE TITLE
typo in left-hand navigation menu

### ISSUE THREAD

**Issue by mromanello** [impresso/impresso.github.io#54]
"Ressources" ->"resources"

<img width="267" alt="Screen Shot 2020-06-12 at 22 10 14" src="https://user-images.githubusercontent.com/310693/84542366-9c757900-acf9-11ea-9b97-7d5c245eedb1.png">

I could try to fix it, but since the typo is also in the URL I fear to break something...

**Comment by PaulSchroeder** [comment]
fixed, thank you !
